/**
 * Maps English relationship type names returned by the API to Spanish display labels.
 * Extend this record as new relationship types are discovered.
 */
export const RELATIONSHIP_LABELS: Record<string, string> = {
  "Principal": "Principal",
  "Partner": "Socio",
  "Employer": "Empleador",
  "Parent": "Padre/madre",
  "Spouse": "Cónyugue",
  "Concubine": "Concubino",
  "Familiar": "Familiar",
  "Employee": "Empleado",
  "Proxy": "Apoderado",
  "Shareholder": "Accionista",
  "President": "Presidente",
  "Director": "Director",
  "Manager": "Gerente",
  "Counselor": "Consejero",
  "Inspector": "Fiscalizador",
  "Unspecified Authority": "Autoridad No Especificada",
  "Member": "Miembro",
  "Protreasurer": "Protesorero",
  "Legal Representative": "Representante Legal",
  "Secretary": "Secretario/a",
  "Auditor": "Revisor",
  "Treasurer": "Tesorero/a",
  "Vice Principal": "Vicedirector",
  "Vice President": "Vicepresidente",
  "Vocal": "Vocal",
  "Deputy Director": "Director Suplente",
  "Deputy Manager": "Gerente Suplente",
  "Alternate Legal Representative": "Representante Legal Suplente",
  "Assistant Manager": "Subgerente",
  "Split Company": "Sociedad Escisionaria",
  "Former Partner": "Ex Socio",
  "Former Director": "Ex Director",
  "Former Manager": "Ex Gerente",
  "Former Administrator": "Ex Administrador",
  "Former Member": "Ex Integrante",
  "Former Owner": "Ex Propietario",
  "Former Legal Representative": "Ex Representante Legal",
  "Former Auditor": "Ex Auditor",
  "Former Vice President": "Ex Vicepresidente",
  "Former Vocal": "Ex Vocal",
  "Former Deputy Director": "Ex Director Suplente",
  "Former Deputy Manager": "Ex Gerente Suplente",
  "Linked Company": "Sociedad Vinculada",
  "Bound": "Vinculado",
  "Notary": "Escribano",
  "Lawyer": "Abogado",
  "Alternate Auditor": "Revisor Suplente",
  "Assignor": "Cedente",
  "Assignee": "Cesionario",
  "Former Deputy Auditor": "Ex Revisor Suplente",
  "Dean": "Decano",
  "Brand Owner": "Titular de Marca",
  "Former Deputy Administrator": "Ex Administrador Suplente",
  "Former Bound": "Ex Vinculado",
  "Auditor ": "Auditor",
  "Internal Auditor": "Auditor Interno",
  "External Auditor": "Auditor Externo",
  "Former External Auditor": "Ex Auditor Externo",
  "Check Signer": "Firmante de Cheques",
  "Administrator": "Administrador",
  "Deputy Administrator": "Administrador Suplente",
  "Deputy Vice President": "Vicepresidente Suplente",
  "Child": "Hijo/a",
  "Former President": "Ex Presidente",
  "Brother": "Hermano",
  "Sister": "Hermana",
  "Cousin": "Primo/a",
  "Friend": "Amigo/a",
}

/**
 * Maps numeric relationship type codes (as used by the API) to Spanish display labels.
 * Used to populate relationship selectors in forms.
 */
export const RELATIONSHIP_OPTIONS: Record<number, string> = {
  1: "Principal",
  3: "Partner",
  4: "Firmante de Cheques",
  5: "Padre/Madre",
  6: "Hijo/a",
  8: "Empleador",
  9: "Cónyuge",
  11: "Concubino",
  12: "Familiar",
  13: "Apoderado",
  14: "Apoderado",
  19: "Accionista",
  20: "Presidente",
  21: "Director",
  22: "Gerente",
  27: "Administrador",
  28: "Consejero",
  33: "Ex Presidente",
  37: "Fiscalizador",
  39: "Autoridad No Especificada",
  40: "Miembro",
  43: "Protesorero",
  44: "Representante Legal",
  46: "Secretario/a",
  47: "Revisor",
  49: "Tesorero/a",
  50: "Vicedirector",
  51: "Vicepresidente",
  52: "Vocal",
  95: "Director Suplente",
  96: "Gerente Suplente",
  97: "Representante Legal Suplente",
  98: "Subgerente",
  100: "Sociedad Escisionaria",
  104: "Ex Socio",
  114: "Ex Director",
  115: "Ex Gerente",
  118: "Ex Administrador",
  126: "Ex Integrante",
  127: "Ex Propietario",
  129: "Ex Representante Legal",
  131: "Ex Auditor",
  135: "Ex Vicepresidente",
  136: "Ex Vocal",
  137: "Ex Director Suplente",
  138: "Ex Gerente Suplente",
  143: "Sociedad Vinculada",
  144: "Vinculado",
  145: "Escribano",
  146: "Abogado",
  149: "Revisor Suplente",
  153: "Cedente",
  154: "Cesionario",
  155: "Ex Revisor Suplente",
  160: "Decano",
  161: "Administrador Suplente",
  163: "Vicepresidente Suplente",
  164: "Titular de Marca",
  168: "Ex Administrador Suplente",
  169: "Ex Vinculado",
  170: "Auditor",
  171: "Auditor Interno",
  172: "Auditor Externo",
  175: "Ex Auditor Externo",
  176: "Empleado",
  1003: "Hermano",
  1004: "Hermana",
  1005: "Primo/a",
  1006: "Amigo/a",
}

/**
 * Returns the Spanish display label for a given English relationship type string.
 * Falls back to the original value if no mapping exists.
 *
 * @param type - Relationship type string as returned by the API
 * @example
 * getRelationshipLabel("President") // → "Presidente"
 * getRelationshipLabel("Unknown")   // → "Unknown"
 */
export function getRelationshipLabel(type: string): string {
  return RELATIONSHIP_LABELS[type] ?? type
}